#docker compose para montar varias imagem de um docker hub repo

version: '3'
services:
  frontend:
    image: 'rierickson/crm-cavalcante:frontend'
    ports:
      - '80:3000'
  vendas_module:
    image: 'rierickson/crm-cavalcante:vendas'
    ports:
      - '8081:3000'
  marketing_module:
    image: 'rierickson/crm-cavalcante:marketing'
    ports:
      - '8082:80'
  # analise_module:
  #   image: 'rierickson/crm-cavalcante:analiseimg'
  #   ports:
  #     - '8083:8083'
